/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientConfig.java
 *
 * Created on Dec 21, 2016, 9:13:59 AM
 */
package tubes_prog;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows 8.1 Pro
 */
public class ClientConfig extends javax.swing.JFrame {
    static String ipserver;
    /** Creates new form ClientConfig */
    public ClientConfig() {
        initComponents();
        mulai.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ip = new javax.swing.JTextField();
        mulai = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        ip.setText("IP Adress Server");
        getContentPane().add(ip);
        ip.setBounds(620, 580, 190, 30);

        mulai.setBackground(new java.awt.Color(51, 51, 51));
        mulai.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        mulai.setForeground(new java.awt.Color(255, 255, 255));
        mulai.setText("Mulai Permainan!");
        mulai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });
        getContentPane().add(mulai);
        mulai.setBounds(620, 630, 190, 50);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Catatan : Pastikan Server yang memulai permainan terlebih dahulu");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(880, 680, 340, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_prog/c3pocar.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setName("cpo"); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(900, 50, 270, 476);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_prog/Stormcar.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setName("strum"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 130, 270, 397);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_prog/r2car.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setName("r2"); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 220, 270, 299);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24));
        jLabel4.setText("Pilih Karaktermu : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(315, 115, 198, 32);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("R2-D2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 540, 30, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Storm Trooper");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 540, 80, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1040, 540, 30, 14);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1354, 698, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes_prog/BG MENUCONFIG.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1366, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    ClientPapan.car="karakter/cpo.gif";mulai.setEnabled(true);
    JOptionPane.showMessageDialog(null,"Kamu memilih CPO sebagai karaktermu di papan permainan");
}//GEN-LAST:event_jLabel3MouseClicked

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    ClientPapan.car="karakter/strum.gif";mulai.setEnabled(true);
    JOptionPane.showMessageDialog(null,"Kamu memilih Strum sebagai karaktermu di papan permainan");
}//GEN-LAST:event_jLabel2MouseClicked

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    ClientPapan.car="karakter/r2.gif";mulai.setEnabled(true);
    JOptionPane.showMessageDialog(null,"Kamu memilih r2 sebagai karaktermu di papan permainan");
}//GEN-LAST:event_jLabel1MouseClicked

private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
    ipserver = ip.getText();
    ClientPapan cp = new ClientPapan();
    cp.setVisible(true);
    
    ClientCh xx = new ClientCh();
     xx.start();   
    this.dispose();
}//GEN-LAST:event_mulaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClientConfig().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mulai;
    // End of variables declaration//GEN-END:variables
}
